#!/bin/bash

ROOTDIR=`pwd`/$(dirname $0)
source $ROOTDIR/utils

# Test cases
ipv4/0001-ipv4-over-veth-pair

ipv6/0001-ipv6-over-veth-pair
ipv6/0002-ipv6-over-sit-veth

bond/0001-bond-802.3ad-veth-pair

gre/0001-gre-ipv4-over-veth-pair
gre/0002-gretap-ipv4-over-veth-pair

macsec/0001-macsec-ipv4-over-veth-pair

vxlan/0001-vxlan-ipv4-over-ipv4-veth-pair
vxlan/0002-vxlan-ipv4-over-ipv4-veth-lwt
vxlan/0003-vxlan-ipv4-over-ipv6-veth-pair
#vxlan/0004-vxlan-ping6-veth-metadata

gnv/0001-geneve-ipv4-over-ipv4-veth-pair
gnv/0002-geneve-ipv4-over-ipv4-veth-lwt
gnv/0003-geneve-ipv4-over-ipv6-veth-pair
gnv/0004-geneve-ipv6-over-ipv6-veth-pair
gnv/0005-geneve-ipv6-over-ipv6-veth-pair2 

vlan/0001-ipv4-over-vlan-veth-pair

ipsec/0001-ipsec-esp4-aead
ipsec/0002-ipsec-esp4-aes-sha1
ipsec/0003-ipsec-ah4
ipsec/0004-ipsec-esp6-aead
ipsec/0005-ipsec-esp6-aes-sha1
ipsec/0006-ipsec-ah6

l2tp/0001-l2tp-udpencap-over-veth-pair
l2tp/0002-l2tp-ipencap-over-veth-pair
