#!/bin/bash

# Use upstream iproute2
export PATH=/usr/local/bin:/home/lrichardson/git/iproute2/ip:/home/lrichardson/git/iperf/src:$PATH
export PATH=/home/lrichard/git/iproute2/ip:$PATH

ROOTDIR=`pwd`/$(dirname $0)
source $ROOTDIR/utils

# Test cases
testfam ipv4
./0001-ipv4-over-veth-pair

testfam ipv6
./0001-ipv6-over-veth-pair
./0002-ipv6-over-sit-veth

testfam gre
./0001-gre-ipv4-over-veth-pair

testfam vxlan
TESTNUM=1 ./vxlan-ipv4-over-ipv4-veth-pair 10
TESTNUM=2 ./vxlan-ipv4-over-ipv4-veth-pair 0
TESTNUM=3 ./vxlan-ipv4-over-ipv4-veth-pair 0xfffffe
TESTNUM=4 ./vxlan-ipv4-over-ipv6-veth-pair 10
TESTNUM=5 ./vxlan-ipv4-over-ipv6-veth-pair 0
TESTNUM=6 ./vxlan-ipv4-over-ipv6-veth-pair 0xfffffe
TESTNUM=7 ./vxlan-ipv4-over-ipv4-veth-lwt  10
TESTNUM=8 ./vxlan-ipv4-over-ipv4-veth-lwt  0
TESTNUM=9 ./vxlan-ipv4-over-ipv4-veth-lwt  0xfffffe

testfam gnv 
TESTNUM=1  ./geneve-ipv4-over-ipv4-veth-pair 10
TESTNUM=2  ./geneve-ipv4-over-ipv4-veth-pair 0
TESTNUM=3  ./geneve-ipv4-over-ipv4-veth-pair 0xfffffe
TESTNUM=4  ./geneve-ipv4-over-ipv6-veth-pair 10
TESTNUM=5  ./geneve-ipv4-over-ipv6-veth-pair 0
TESTNUM=6  ./geneve-ipv4-over-ipv6-veth-pair 0xfffffe
TESTNUM=7  ./geneve-ipv4-over-ipv4-veth-lwt  10
TESTNUM=8  ./geneve-ipv4-over-ipv4-veth-lwt  0
TESTNUM=9  ./geneve-ipv4-over-ipv4-veth-lwt  0xfffffe
TESTNUM=10 ./geneve-ipv6-over-ipv6-veth-pair 10
TESTNUM=11 ./geneve-ipv6-over-ipv6-veth-pair 0
TESTNUM=12 ./geneve-ipv6-over-ipv6-veth-pair 0xfffffe
TESTNUM=10 ./geneve-ipv6-over-ipv6-veth-pair2 10
TESTNUM=11 ./geneve-ipv6-over-ipv6-veth-pair2 0
TESTNUM=12 ./geneve-ipv6-over-ipv6-veth-pair2 0xfffffe
