#!/bin/bash
TESTFAM=l2tp
source $(dirname $0)/../utils

#                 ................................................. 
echo -n "$TESTID: ipv4 over l2tp/ip tunnel over veth pair ........."
PASSED=true
##############################################################################
modprobe l2tp_eth
modprobe l2tp_ip

# Setup
ip netns add ns0
ip netns add ns1

# Create and configure veth pair
ip link add p0 type veth peer name p1

ip link set p0 netns ns0
ip netns exec ns0 ip addr add "1.1.1.1/24" dev p0
ip netns exec ns0 ip link set dev p0 up

ip link set p1 netns ns1
ip netns exec ns1 ip addr add "1.1.1.2/24" dev p1
ip netns exec ns1 ip link set dev p1 up

# Create and configure tunnel endpoints
ip netns exec ns0 ip l2tp add tunnel tunnel_id 1 peer_tunnel_id 1 encap ip local 1.1.1.1 remote 1.1.1.2
ip netns exec ns0 ip l2tp add session tunnel_id 1 session_id 1 peer_session_id 1
ip netns exec ns0 ip link set dev l2tpeth0 up mtu 1450
ip netns exec ns0 ip addr add "4.1.1.1/24" dev l2tpeth0

ip netns exec ns1 ip l2tp add tunnel tunnel_id 1 peer_tunnel_id 1 encap ip local 1.1.1.2 remote 1.1.1.1
ip netns exec ns1 ip l2tp add session tunnel_id 1 session_id 1 peer_session_id 1
ip netns exec ns1 ip link set dev l2tpeth0 up mtu 1450
ip netns exec ns1 ip addr add "4.1.1.2/24" dev l2tpeth0

##############################################################################
# Execution
chk_ping_ipv4 ns0 4.1.1.2         || PASSED=false
chk_iperf_tcpv4 ns0 ns1 4.1.1.2   || PASSED=false

##############################################################################
# Cleanup
ip netns del ns0
ip netns del ns1

##############################################################################
# Result
if $PASSED ; then
    echo " [PASS]"
else
    echo " [FAIL]"
fi
