#!/bin/bash
TESTFAM=macsec
source $(dirname $0)/../utils

#                 ................................................. 
echo -n "$TESTID: ipv4 over macsec tunnel over veth pair..........."
PASSED=true
##############################################################################
# Setup
ip netns add ns0
ip netns add ns1

# Create and configure veth pair
ip link add p0 type veth peer name p1

ip link set p0 netns ns0
ip netns exec ns0 ip link set p0 address 04:00:00:11:11:11
ip netns exec ns0 ip link set dev p0 up
ip netns exec ns0 ip link add link p0 macsec0 type macsec
ip netns exec ns0 ip macsec add macsec0 tx sa 0 pn 100 on key 01 11111111111111111111111111111111
ip netns exec ns0 ip macsec add macsec0 rx address 04:00:00:22:22:22 port 1
ip netns exec ns0 ip macsec add macsec0 rx address 04:00:00:22:22:22 port 1 sa 0 pn 100 on key 02 22222222222222222222222222222222
ip netns exec ns0 ip link set dev macsec0 up
ip netns exec ns0 ip addr add "1.1.1.1/24" dev macsec0

ip link set p1 netns ns1
ip netns exec ns1 ip link set p1 address 04:00:00:22:22:22
ip netns exec ns1 ip link set dev p1 up
ip netns exec ns1 ip link add link p1 macsec0 type macsec
ip netns exec ns1 ip macsec add macsec0 tx sa 0 pn 100 on key 02 22222222222222222222222222222222
ip netns exec ns1 ip macsec add macsec0 rx address 04:00:00:11:11:11 port 1
ip netns exec ns1 ip macsec add macsec0 rx address 04:00:00:11:11:11 port 1 sa 0 pn 100 on key 01 11111111111111111111111111111111
ip netns exec ns1 ip link set dev macsec0 up
ip netns exec ns1 ip addr add "1.1.1.2/24" dev macsec0

##############################################################################
# Execution
chk_ping_ipv4 ns0 1.1.1.2         || PASSED=false
chk_iperf_tcpv4 ns0 ns1 1.1.1.2   || PASSED=false

##############################################################################
# Cleanup
ip netns del ns0
ip netns del ns1

##############################################################################
# Result
if $PASSED ; then
    echo " [PASS]"
else
    echo " [FAIL]"
fi
