#!/bin/bash
TESTFAM=ipsec
source $(dirname $0)/../utils
source $(dirname $0)/config

echo -n "$TESTID: IPv4 AH in transport mode with SHA1.............."
PASSED=true
##############################################################################
# Setup
ip netns add ns0
ip netns add ns1

# Create and configure veth pair
ip link add p0 type veth peer name p1

ip link set p0 netns ns0
ip netns exec ns0 ip link set dev p0 up

ip0=$ipv4_0
ip1=$ipv4_1

ip netns exec ns0 ip xfrm state  add src $ip1 dst $ip0 proto ah spi $spi1  auth sha1 $sha1  mode transport sel src $ip1 dst $ip0
ip netns exec ns0 ip xfrm policy add src $ip1 dst $ip0 dir in  tmpl src $ip1 dst $ip0 proto ah mode transport
ip netns exec ns0 ip xfrm state  add src $ip0 dst $ip1 proto ah spi $spi0 auth sha1 $sha0 mode transport sel src $ip0 dst $ip1
ip netns exec ns0 ip xfrm policy add src $ip0 dst $ip1 dir out tmpl src $ip0 dst $ip1 proto ah mode transport
ip netns exec ns0 ip addr add $ip0/24 dev p0

ip link set p1 netns ns1
ip netns exec ns1 ip link set dev p1 up

ip netns exec ns1 ip xfrm state  add src $ip0 dst $ip1 proto ah spi $spi0  auth sha1 $sha0  mode transport sel src $ip0 dst $ip1
ip netns exec ns1 ip xfrm policy add src $ip0 dst $ip1 dir in  tmpl src $ip0 dst $ip1 proto ah mode transport
ip netns exec ns1 ip xfrm state  add src $ip1 dst $ip0 proto ah spi $spi1 auth sha1 $sha1 mode transport sel src $ip1 dst $ip0
ip netns exec ns1 ip xfrm policy add src $ip1 dst $ip0 dir out tmpl src $ip1 dst $ip0 proto ah mode transport
ip netns exec ns1 ip addr add $ip1/24 dev p1

##############################################################################
# Execution
chk_ping_ipv4 ns0 $ip1         || PASSED=false
chk_iperf_tcpv4 ns0 ns1 $ip1   || PASSED=false

##############################################################################
# Cleanup
ip netns del ns0
ip netns del ns1

##############################################################################
# Result
if $PASSED ; then
    echo " [PASS]"
else
    echo " [FAIL]"
fi
