#!/bin/bash
TESTFAM=ipsec
source $(dirname $0)/../utils
source $(dirname $0)/config

echo -n "$TESTID: IPv6 ESP in transport mode with AEAD............."
PASSED=true
##############################################################################
# Setup
ip netns add ns0
ip netns add ns1

# Create and configure veth pair
ip link add p0 type veth peer name p1

ip link set p0 netns ns0
ip netns exec ns0 ip link set dev p0 up
ip netns exec ns0 bash -c "echo 0 > /proc/sys/net/ipv6/conf/p0/accept_dad"

ip0=$ipv6_0
ip1=$ipv6_1

ip netns exec ns0 ip xfrm state  add src $ip1 dst $ip0 proto esp spi $spi1  aead $aead_algo $aead1 $aead_icvlen  mode transport sel src $ip1 dst $ip0
ip netns exec ns0 ip xfrm policy add src $ip1 dst $ip0 dir in  tmpl src $ip1 dst $ip0 proto esp mode transport action allow
ip netns exec ns0 ip xfrm state  add src $ip0 dst $ip1 proto esp spi $spi0  aead $aead_algo $aead0 $aead_icvlen  mode transport sel src $ip0 dst $ip1
ip netns exec ns0 ip xfrm policy add src $ip0 dst $ip1 dir out tmpl src $ip0 dst $ip1 proto esp mode transport action allow
ip netns exec ns0 ip addr add $ip0/96 dev p0

ip link set p1 netns ns1
ip netns exec ns1 ip link set dev p1 up
ip netns exec ns1 bash -c "echo 0 > /proc/sys/net/ipv6/conf/p1/accept_dad"

ip netns exec ns1 ip xfrm state  add src $ip0 dst $ip1 proto esp spi $spi0   aead $aead_algo $aead0 $aead_icvlen  mode transport sel src $ip0 dst $ip1
ip netns exec ns1 ip xfrm policy add src $ip0 dst $ip1 dir in  tmpl src $ip0 dst $ip1 proto esp mode transport action allow
ip netns exec ns1 ip xfrm state  add src $ip1 dst $ip0 proto esp spi $spi1   aead $aead_algo $aead1 $aead_icvlen  mode transport sel src $ip1 dst $ip0
ip netns exec ns1 ip xfrm policy add src $ip1 dst $ip0 dir out tmpl src $ip1 dst $ip0 proto esp mode transport action allow
ip netns exec ns1 ip addr add $ip1/96 dev p1

##############################################################################
# Execution
chk_ping_ipv6 ns0 $ip1         || PASSED=false
chk_iperf_tcpv4 ns0 ns1 $ip1   || PASSED=false

##############################################################################
# Cleanup
ip netns del ns0
ip netns del ns1

##############################################################################
# Result
if $PASSED ; then
    echo " [PASS]"
else
    echo " [FAIL]"
fi
